server:
  port: ${PORT}

spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/elielbatiston/ead-config-server-repo"
          default-label: main
#          username: ${GIT_USERNAME}
#          password: ${GIT_PASSWORD}

encrypt:
  key: mlMnl+9/CrzMvmIvRHxsHUTM5I/snoFZ62jRwa2/QLgKUxBruy1ymBgfV6EiPMYf

ead:
  configServer:
    username: ${CONFIG_SERVER_USERNAME}
    password: ${CONFIG_SERVER_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${APP_DOMAIN_NAME}
    non-secure-port: 80
